# Generated by Django 4.1.3 on 2022-11-26 18:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100, verbose_name='銘柄名')),
                ('buy', models.PositiveIntegerField(blank=True, null=True, verbose_name='買値')),
                ('sell', models.PositiveIntegerField(blank=True, null=True, verbose_name='売値')),
            ],
        ),
        migrations.CreateModel(
            name='StockPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.PositiveIntegerField(verbose_name='株数')),
                ('email', models.EmailField(max_length=255, verbose_name='連絡先メールアドレス')),
                ('name', models.CharField(max_length=255, verbose_name='お名前')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='取引日時')),
                ('stock_price', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stock.stockprice', verbose_name='銘柄名')),
            ],
        ),
    ]
