# Generated by Django 4.1.3 on 2022-12-10 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Metal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='金属名')),
                ('buy', models.PositiveIntegerField(blank=True, null=True, verbose_name='買値')),
                ('sell', models.PositiveIntegerField(blank=True, null=True, verbose_name='売値')),
            ],
        ),
        migrations.CreateModel(
            name='MetalPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.PositiveIntegerField(blank=True, null=True, verbose_name='重量')),
                ('email', models.CharField(max_length=255, verbose_name='email')),
                ('name', models.CharField(max_length=255, verbose_name='取引者')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='取引日時')),
                ('metal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='metal.metal', verbose_name='金属名')),
            ],
        ),
    ]
