# Generated by Django 4.1.3 on 2022-11-26 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metal', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MetalPrice',
            new_name='Metal',
        ),
        migrations.RenameField(
            model_name='metal',
            old_name='metal_type',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='metalpurchase',
            old_name='metal_type',
            new_name='metal',
        ),
    ]
