# Generated by Django 4.1.3 on 2022-11-26 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metal', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MetalPrice',
            new_name='MetalType',
        ),
        migrations.RenameField(
            model_name='metaltype',
            old_name='metal_type',
            new_name='metal_name',
        ),
        migrations.AlterModelTable(
            name='metalpurchase',
            table=None,
        ),
        migrations.AlterModelTable(
            name='metaltype',
            table=None,
        ),
    ]
